CREATE TABLE "cards" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL UNIQUE,
	"hp"	BLOB NOT NULL DEFAULT 0,
	"maxHp"	INTEGER NOT NULL DEFAULT 1,
	"dmg"	INTEGER NOT NULL DEFAULT 0,
	"cost"	INTEGER NOT NULL DEFAULT 0,
	"rarity"	TEXT NOT NULL DEFAULT 'Common' CHECK("rarity" IN ('Common', 'Rare', 'Epic', 'Legendary', 'Hero')),
	"modifiers"	TEXT NOT NULL DEFAULT 'None' CHECK("modifiers" IN ('None', 'Laser', 'Rapid', 'Zlatni', 'Reverse', 'Wide')),
	"baseAttack"	TEXT NOT NULL DEFAULT 'Chomper' CHECK("baseAttack" IN ('Chomper', 'Peashooter', 'Catapult', 'Nut', 'Jelepeno', 'Pijavica')),
	"image"	TEXT,
	"cooldown"	INTEGER NOT NULL DEFAULT 0,
	"stunned"	INTEGER NOT NULL DEFAULT 0,
	"hitCount"	INTEGER NOT NULL DEFAULT 0,
	"age"	INTEGER NOT NULL DEFAULT 0,
	"hitShield"	INTEGER NOT NULL DEFAULT 0,
	"killCounter"	INTEGER NOT NULL DEFAULT 0,
	"pumpica"	INTEGER NOT NULL DEFAULT 0,
	"placementType"	TEXT NOT NULL DEFAULT 'Normal',
	"lokacija"	TEXT DEFAULT 'None',
	"species"	TEXT NOT NULL DEFAULT 'Human',
	"owner"	TEXT DEFAULT NULL,
	"description"	TEXT DEFAULT '',
	"faceup"	INTEGER NOT NULL DEFAULT 0,
	"musko"	INTEGER NOT NULL DEFAULT 1,
	"gay"	INTEGER NOT NULL DEFAULT 0,
	"immune"	TEXT NOT NULL DEFAULT 0,
	"ignoresTileRules"	NUMERIC NOT NULL DEFAULT 0,
	"plotTwist"	REAL NOT NULL DEFAULT 0,
	"quickAttack"	INTEGER NOT NULL DEFAULT 0,
	"indestructible"	INTEGER NOT NULL DEFAULT 0,
	"abilityParams"	TEXT DEFAULT '{}',
	PRIMARY KEY("id" AUTOINCREMENT)
);